package gui;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import pojo.Userprofile;

public class AdminOptionFrame extends javax.swing.JFrame {

    public AdminOptionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Image img = tk.getImage("C:/Users/Sunakshi Sharma/OneDrive/Pictures/project/icon.png");
        this.setIconImage(img);
        this.setTitle("online exam application");
        lblUsername.setText("welcome  "+ Userprofile.getUserid());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbSetPaper = new javax.swing.JRadioButton();
        rbEditPaper = new javax.swing.JRadioButton();
        rbRegisterSt = new javax.swing.JRadioButton();
        rbViewScore = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 350));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("online quiz admin pannel");

        rbSetPaper.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbSetPaper);
        rbSetPaper.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbSetPaper.setForeground(new java.awt.Color(255, 153, 0));
        rbSetPaper.setText("set a paper");
        rbSetPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSetPaperActionPerformed(evt);
            }
        });

        rbEditPaper.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbEditPaper);
        rbEditPaper.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbEditPaper.setForeground(new java.awt.Color(255, 153, 0));
        rbEditPaper.setText("edit paper");
        rbEditPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEditPaperActionPerformed(evt);
            }
        });

        rbRegisterSt.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbRegisterSt);
        rbRegisterSt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbRegisterSt.setForeground(new java.awt.Color(255, 153, 0));
        rbRegisterSt.setText("register student");
        rbRegisterSt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRegisterStActionPerformed(evt);
            }
        });

        rbViewScore.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbViewScore);
        rbViewScore.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbViewScore.setForeground(new java.awt.Color(255, 153, 0));
        rbViewScore.setText("view score");
        rbViewScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbViewScoreActionPerformed(evt);
            }
        });

        btnDoTask.setBackground(new java.awt.Color(51, 51, 51));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 153, 0));
        btnDoTask.setText("do task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(51, 51, 51));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 153, 0));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbViewScore)
                            .addComponent(rbRegisterSt)
                            .addComponent(rbEditPaper)
                            .addComponent(rbSetPaper))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSetPaper)
                .addGap(18, 18, 18)
                .addComponent(rbEditPaper)
                .addGap(18, 18, 18)
                .addComponent(rbRegisterSt)
                .addGap(20, 20, 20)
                .addComponent(rbViewScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoTask)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbRegisterStActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRegisterStActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRegisterStActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"logging out ","logout",JOptionPane.CLOSED_OPTION);
        LoginFrame loginFr = new LoginFrame();
        loginFr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void rbSetPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSetPaperActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_rbSetPaperActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
        // TODO add your handling code here:
        if(rbSetPaper.isSelected())
        {
        SetPaperFrame paper = new SetPaperFrame();
        paper.setVisible(true);    
        }
        else if(rbEditPaper.isSelected())
        {
        EditPaperFrame edit = new EditPaperFrame();
        edit.setVisible(true);
        }
        else if(rbRegisterSt.isSelected())
        {
        RegisterStudentFrame st = new RegisterStudentFrame();
        st.setVisible(true);
        }
        else if(rbViewScore.isSelected())
        {
        ViewScoreFrame view = new ViewScoreFrame();
        view.setVisible(true);
        }
        else 
        {
        JOptionPane.showMessageDialog(null,"please choose any of the option ","error!",JOptionPane.ERROR_MESSAGE);
        return;
        }
        this.dispose();
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void rbEditPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEditPaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEditPaperActionPerformed

    private void rbViewScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbViewScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbViewScoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.JButton btnLogout;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JRadioButton rbEditPaper;
    private javax.swing.JRadioButton rbRegisterSt;
    private javax.swing.JRadioButton rbSetPaper;
    private javax.swing.JRadioButton rbViewScore;
    // End of variables declaration//GEN-END:variables
}
